# Site settings
title: Greg Osuri
email: me@gregosuri.com
description: > # this means to ignore newlines until "baseurl:"
  I build things for people that build things
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://gregosuri.com" # the base hostname & protocol for your site
twitter_username: kn0tch
github_username:  gosuri

# Build settings
markdown: kramdown

permalink: pretty

paginate: 5

karmadown:
  enable_coreray: true
