---
version: "2.0"

services:
  web:
    image: gosuri/blog:v2
    expose:
      - port: 8080
        as: 80
        accept:
          - gregosuri.com
          - gregosuri
        to:
          - global: true

profiles:
  compute:
    web:
      resources:
        cpu:
          units: 0.1
        memory:
          size: 512Mi
        storage:
          size: 512Mi
  placement:
    westcoast:
      attributes:
        host: akash
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
      pricing:
        web: 
          denom: uakt
          amount: 10

deployment:
  web:
    westcoast:
      profile: web
      count: 1
